### ISSUE TITLE
Base64 non-compliant with RFC

### ISSUE THREAD

**Issue by Maozerhouni** [semente/python-baseconv#7]
Hi. Thanks for this project.
What is the conversation table used for converting in base64 ? It seems not compliant with RFC2045. 0 is traduced to 0, and A is traduced to 10.
https://tools.ietf.org/html/rfc2045#page-24

**Comment by stephenwade** [comment]
This code is concerned with converting numbers between bases, not encoding text, so it won't be compliant with a text encoding standard.

You can see the base64 alphabet used here:
https://github.com/semente/python-baseconv/blob/7007e825959346a5ba456d8971b89626da7dcb38/baseconv.py#L84-L85

**Comment by semente** [comment]
Hey @Maozerhouni! Stephen is right but if you wish you can use a different alphapet by creating a new BaseConverter: `BaseConverter(digits='myalphabethere')`
